

export const dataHistorialResolucionTarea = [
    {
        id:1,
        nombreTarea: 'uno',
        fechaIngreso: '12-12-2024',
        fechaRespuesta: '13-12-2024',
        status: 'Aceptada',
        discrepancia1: 'primera',
        discrepancia2: 'segunda',
        discrepancia3: 'tercera',
        discrepancia4: 'cuarta',
    },
    {
        id:2,
        nombreTarea: 'dos',
        fechaIngreso: '12-12-2024',
        fechaRespuesta: '13-12-2024',
        status: 'Aceptada',
        discrepancia1: 'primera',
        discrepancia2: 'segunda',
        discrepancia3: 'tercera',
        discrepancia4: 'cuarta',
    },
    {
        id:3,
        nombreTarea: 'tres',
        fechaIngreso: '12-12-2024',
        fechaRespuesta: '13-12-2024',
        status: 'Aceptada',
        discrepancia1: 'primera',
        discrepancia2: 'segunda',
        discrepancia3: 'tercera',
        discrepancia4: 'cuarta',
    },
    {
        id:4,
        nombreTarea: 'cuatro',
        fechaIngreso: '12-12-2024',
        fechaRespuesta: '13-12-2024',
        status: 'Aceptada',
        discrepancia1: 'primera',
        discrepancia2: 'segunda',
        discrepancia3: 'tercera',
        discrepancia4: 'cuarta',
    },
    {
        id:1,
        nombreTarea: 'uno',
        fechaIngreso: '12-12-2024',
        fechaRespuesta: '13-12-2024',
        status: 'Aceptada',
        discrepancia1: 'primera',
        discrepancia2: 'segunda',
        discrepancia3: 'tercera',
        discrepancia4: 'cuarta',
    },
    {
        id:2,
        nombreTarea: 'dos',
        fechaIngreso: '12-12-2024',
        fechaRespuesta: '13-12-2024',
        status: 'Aceptada',
        discrepancia1: 'primera',
        discrepancia2: 'segunda',
        discrepancia3: 'tercera',
        discrepancia4: 'cuarta',
    },
    {
        id:3,
        nombreTarea: 'tres',
        fechaIngreso: '12-12-2024',
        fechaRespuesta: '13-12-2024',
        status: 'Aceptada',
        discrepancia1: 'primera',
        discrepancia2: 'segunda',
        discrepancia3: 'tercera',
        discrepancia4: 'cuarta',
    },
    {
        id:4,
        nombreTarea: 'cuatro',
        fechaIngreso: '12-12-2024',
        fechaRespuesta: '13-12-2024',
        status: 'Aceptada',
        discrepancia1: 'primera',
        discrepancia2: 'segunda',
        discrepancia3: 'tercera',
        discrepancia4: 'cuarta',
    },
    {
        id:1,
        nombreTarea: 'uno',
        fechaIngreso: '12-12-2024',
        fechaRespuesta: '13-12-2024',
        status: 'Aceptada',
        discrepancia1: 'primera',
        discrepancia2: 'segunda',
        discrepancia3: 'tercera',
        discrepancia4: 'cuarta',
    },
    {
        id:2,
        nombreTarea: 'dos',
        fechaIngreso: '12-12-2024',
        fechaRespuesta: '13-12-2024',
        status: 'Aceptada',
        discrepancia1: 'primera',
        discrepancia2: 'segunda',
        discrepancia3: 'tercera',
        discrepancia4: 'cuarta',
    },
    {
        id:3,
        nombreTarea: 'tres',
        fechaIngreso: '12-12-2024',
        fechaRespuesta: '13-12-2024',
        status: 'Aceptada',
        discrepancia1: 'primera',
        discrepancia2: 'segunda',
        discrepancia3: 'tercera',
        discrepancia4: 'cuarta',
    },
    {
        id:4,
        nombreTarea: 'cuatro',
        fechaIngreso: '12-12-2024',
        fechaRespuesta: '13-12-2024',
        status: 'Aceptada',
        discrepancia1: 'primera',
        discrepancia2: 'segunda',
        discrepancia3: 'tercera',
        discrepancia4: 'cuarta',
    },
    {
        id:1,
        nombreTarea: 'uno',
        fechaIngreso: '12-12-2024',
        fechaRespuesta: '13-12-2024',
        status: 'Aceptada',
        discrepancia1: 'primera',
        discrepancia2: 'segunda',
        discrepancia3: 'tercera',
        discrepancia4: 'cuarta',
    },
    {
        id:2,
        nombreTarea: 'dos',
        fechaIngreso: '12-12-2024',
        fechaRespuesta: '13-12-2024',
        status: 'Aceptada',
        discrepancia1: 'primera',
        discrepancia2: 'segunda',
        discrepancia3: 'tercera',
        discrepancia4: 'cuarta',
    },
    {
        id:3,
        nombreTarea: 'tres',
        fechaIngreso: '12-12-2024',
        fechaRespuesta: '13-12-2024',
        status: 'Aceptada',
        discrepancia1: 'primera',
        discrepancia2: 'segunda',
        discrepancia3: 'tercera',
        discrepancia4: 'cuarta',
    },
    {
        id:4,
        nombreTarea: 'cuatro',
        fechaIngreso: '12-12-2024',
        fechaRespuesta: '13-12-2024',
        status: 'Aceptada',
        discrepancia1: 'primera',
        discrepancia2: 'segunda',
        discrepancia3: 'tercera',
        discrepancia4: 'cuarta',
    },
    {
        id:1,
        nombreTarea: 'uno',
        fechaIngreso: '12-12-2024',
        fechaRespuesta: '13-12-2024',
        status: 'Aceptada',
        discrepancia1: 'primera',
        discrepancia2: 'segunda',
        discrepancia3: 'tercera',
        discrepancia4: 'cuarta',
    },
    {
        id:2,
        nombreTarea: 'dos',
        fechaIngreso: '12-12-2024',
        fechaRespuesta: '13-12-2024',
        status: 'Aceptada',
        discrepancia1: 'primera',
        discrepancia2: 'segunda',
        discrepancia3: 'tercera',
        discrepancia4: 'cuarta',
    },
    {
        id:3,
        nombreTarea: 'tres',
        fechaIngreso: '12-12-2024',
        fechaRespuesta: '13-12-2024',
        status: 'Aceptada',
        discrepancia1: 'primera',
        discrepancia2: 'segunda',
        discrepancia3: 'tercera',
        discrepancia4: 'cuarta',
    },
    {
        id:4,
        nombreTarea: 'cuatro',
        fechaIngreso: '12-12-2024',
        fechaRespuesta: '13-12-2024',
        status: 'Aceptada',
        discrepancia1: 'primera',
        discrepancia2: 'segunda',
        discrepancia3: 'tercera',
        discrepancia4: 'cuarta',
    },
    {
        id:1,
        nombreTarea: 'uno',
        fechaIngreso: '12-12-2024',
        fechaRespuesta: '13-12-2024',
        status: 'Aceptada',
        discrepancia1: 'primera',
        discrepancia2: 'segunda',
        discrepancia3: 'tercera',
        discrepancia4: 'cuarta',
    },
    {
        id:2,
        nombreTarea: 'dos',
        fechaIngreso: '12-12-2024',
        fechaRespuesta: '13-12-2024',
        status: 'Aceptada',
        discrepancia1: 'primera',
        discrepancia2: 'segunda',
        discrepancia3: 'tercera',
        discrepancia4: 'cuarta',
    },
    {
        id:3,
        nombreTarea: 'tres',
        fechaIngreso: '12-12-2024',
        fechaRespuesta: '13-12-2024',
        status: 'Aceptada',
        discrepancia1: 'primera',
        discrepancia2: 'segunda',
        discrepancia3: 'tercera',
        discrepancia4: 'cuarta',
    },
    {
        id:4,
        nombreTarea: 'cuatro',
        fechaIngreso: '12-12-2024',
        fechaRespuesta: '13-12-2024',
        status: 'Aceptada',
        discrepancia1: 'primera',
        discrepancia2: 'segunda',
        discrepancia3: 'tercera',
        discrepancia4: 'cuarta',
    },
    {
        id:1,
        nombreTarea: 'uno',
        fechaIngreso: '12-12-2024',
        fechaRespuesta: '13-12-2024',
        status: 'Aceptada',
        discrepancia1: 'primera',
        discrepancia2: 'segunda',
        discrepancia3: 'tercera',
        discrepancia4: 'cuarta',
    },
    {
        id:2,
        nombreTarea: 'dos',
        fechaIngreso: '12-12-2024',
        fechaRespuesta: '13-12-2024',
        status: 'Aceptada',
        discrepancia1: 'primera',
        discrepancia2: 'segunda',
        discrepancia3: 'tercera',
        discrepancia4: 'cuarta',
    },
    {
        id:3,
        nombreTarea: 'tres',
        fechaIngreso: '12-12-2024',
        fechaRespuesta: '13-12-2024',
        status: 'Aceptada',
        discrepancia1: 'primera',
        discrepancia2: 'segunda',
        discrepancia3: 'tercera',
        discrepancia4: 'cuarta',
    },
    {
        id:4,
        nombreTarea: 'cuatro',
        fechaIngreso: '12-12-2024',
        fechaRespuesta: '13-12-2024',
        status: 'Aceptada',
        discrepancia1: 'primera',
        discrepancia2: 'segunda',
        discrepancia3: 'tercera',
        discrepancia4: 'cuarta',
    },
]